name: API and Web Automation Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-automation-tests:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    # Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup Java
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Install dependencies
    - name: Install dependencies
      run: ./gradlew build

    # Run API Tests
    - name: Run API Tests
      run: ./gradlew test --tests runner.ApiTest

    # Upload API Test Results
    - name: Upload API Test Results
      uses: actions/upload-artifact@v4
      with:
        name: api-test-results
        path: build/reports/tests/test/

    # Setup Chrome for UI Tests
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest

    # Run UI Tests
    - name: Run Web Tests
      run: ./gradlew test --tests runner.WebTest

    # Upload UI Test Results
    - name: Upload UI Test Results
      uses: actions/upload-artifact@v4
      with:
        name: web-test-results
        path: build/reports/tests/test/
      
    # Archive Test Result
    - name: Archive Test Result
      uses: actions/upload-artifact@v4.6.0
      if: always()
      with:
        name: Cucumber Report
        path: reports

    # Deploy to Github Pages
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./reports
        publish_branch: gh-pages
