name: API and Web Automation Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-automation-tests:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    # Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup Java
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Grant execute permission to gradlew
    - name: Grant execute permission to gradlew
      run: chmod +x gradlew

    # Setup Chrome for UI Tests
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest

    # Install dependencies
    - name: Install dependencies
      run: ./gradlew build --no-daemon

    # Execute API Tests
    - name: Execute API Tests
      run: ./gradlew test --tests runner.ApiTest --no-daemon

    # Execute UI Tests
    - name: Execute UI Tests
      run: ./gradlew test --tests runner.UiTest --no-daemon

    # Archive Test Results
    - name: Archive Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Test Results
        path: build/reports

    # Deploy to Github Pages
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./reports
        publish_branch: gh-pages
